name: einblicke_app
description: The companion app for e-ink picture frames running Einblicke

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  gap: ^3.0.1
  flutter_bloc: ^8.1.3
  http: ^1.1.2
  get_it: ^8.0.2
  dio: ^5.4.0
  flutter_secure_storage: ^9.0.0
  image_picker: ^1.0.5
  permission_handler: ^11.3.1
  http_parser: ^4.0.2
  image: ^4.1.3
  image_cropper: ^8.0.2
  go_router: ^14.6.1
  flutter_carousel_widget: ^3.1.0
  equatable: ^2.0.5
  einblicke_shared:
    path: ../einblicke_shared/
  einblicke_shared_clients:
    path: ../einblicke_shared_clients/
  dartz: ^0.10.1
  mocktail: ^1.0.3
  shared_preferences: ^2.2.2
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  file: ^7.0.0
  sprung: ^3.0.1
  device_info_plus: ^11.1.1
  apple_product_name: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8

flutter:
  generate: true

  assets:
    - assets/images/unlicensed/

flutter_launcher_icons:
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_icon.png"
