name: dispatch_pi_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  flutter_localizations:
    sdk: flutter
  gap: ^3.0.1
  flutter_bloc: ^8.1.3
  http: ^1.1.2
  get_it: ^7.6.4
  dio: ^5.4.0
  flutter_secure_storage: ^9.0.0
  image_picker: ^1.0.5
  permission_handler: ^10.4.5
  http_parser: ^4.0.2
  image: ^4.1.3
  image_cropper: ^5.0.1
  go_router: ^13.0.1
  sheet:
    git:
      url: https://github.com/jamesblasco/modal_bottom_sheet
      ref: d5c9ceb
      path: sheet/
  infinite_carousel: ^1.0.3
  flutter_carousel_widget: ^2.2.0
  equatable: ^2.0.5
  dispatch_pi_shared:
    path: ../dispatch_pi_shared/
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^2.0.0

flutter:
  generate: true

  assets:
    - assets/images/unlicensed/

flutter_launcher_icons:
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_icon.png"